name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for Api project
      run: dotnet restore src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj
    - name: Build Api project
      run: dotnet build --no-restore src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj
    - name: Test Api project
      run: dotnet test --no-build --verbosity normal src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj

    - name: Generate NuGet packages
      run: |
        dotnet pack src/AspNetCoreAPI-GitHubAction.Api/AspNetCoreAPI-GitHubAction.Api.csproj --output nupkgs
        ls nupkgs # List the contents of the output directory to verify that packages were generated

    - name: Create destination folder
      run: mkdir -p $HOME/Desktop/packages

    - name: Move NuGet packages to destination folder
      run: mv nupkgs/*.nupkg $HOME/Desktop/packages

    - name: Publish package
      run: dotnet nuget push $HOME/Desktop/packages/*.nupkg --source "https://nuget.pkg.github.com/pravesh-77/index.json" --api-key ${{ secrets.DotNet_Token }} --skip-duplicate

    - name: Archive NuGet packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: $HOME/Desktop/packages

  download:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: nuget-packages
        path: $HOME/Desktop/packages
