name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies for Api project
      run: dotnet restore
      working-directory: src/AspNetCoreAPI-GitHubAction.Api
    - name: Build Api project
      run: dotnet build --no-restore
      working-directory: src/AspNetCoreAPI-GitHubAction.Api
    - name: Test Api project
      run: dotnet test --no-build --verbosity normal
      working-directory: src/AspNetCoreAPI-GitHubAction.Api

    - name: Restore dependencies for Test project
      run: dotnet restore
      working-directory: src/AspNetCoreAPI-GitHubAction.Test
    - name: Build Test project
      run: dotnet build --no-restore
      working-directory: src/AspNetCoreAPI-GitHubAction.Test
    - name: Test Test project
      run: dotnet test --no-build --verbosity normal
      working-directory: src/AspNetCoreAPI-GitHubAction.Test
